**多次元配列**

In [2]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

print(np.ndim(A))

print(A.shape)

print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [5]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)

print(np.ndim(B))

print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


**行列の積**

In [7]:
A = np.array([[1,2],[3,4]])
print(A.shape)
B = np.array([[5,6],[7,8]])
print(B.shape)

print(np.dot(A,B))    ##内積

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [8]:
A = np.array([[1,2,3],[4,5,6]])
print(A.shape)
B = np.array([[1,2],[3,4],[5,6]])
print(B.shape)

print(np.dot(A,B))    ##内積

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [9]:
C=np.array([[1,2],[3,4]])
print(C.shape)
print(A.shape)
np.dot(A,C)

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [11]:
A=np.array([[1,2],[3,4],[5,6]])
print(A.shape)
B=np.array([7,8])
print(B.shape)
print(np.dot(A,B))

(3, 2)
(2,)
[23 53 83]


**ニューラルネットワークの行列の積**

In [13]:
X=np.array([1,2])
print(X.shape)
W=np.array([[1,3,5],[2,4,6]])
print(W)
print(W.shape)

(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [14]:
Y=np.dot(X,W)
print(Y)

[ 5 11 17]
