**例**

In [5]:
import numpy as np

a=np.array([0.3,2.9,4.0])

exp_a=np.exp(a)
print(exp_a)
sum_exp_a=np.sum(exp_a)
print(sum_exp_a)
y=exp_a/sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


**ソフトマックス**

In [4]:
def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a=np.sum(exp_a)
  y=exp_a/sum_exp_a
  return y

**ソフトマックス関数のオーバーフロー対策**

In [6]:
##overflow
a=np.array([1010,1000,990])
print(np.exp(a)/np.sum(np.exp(a)))

[nan nan nan]


/tmp/ipykernel_3213/227512381.py:3: RuntimeWarning: overflow encountered in exp
  print(np.exp(a)/np.sum(np.exp(a)))
/tmp/ipykernel_3213/227512381.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.exp(a)/np.sum(np.exp(a)))


In [7]:
c=np.max(a)
print(a-c)

[  0 -10 -20]


In [9]:
np.exp(a-c)/np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

**オーバーフロー対策したソフトマックス関数**

In [10]:
def softmax(a):
  c=np.max(a)
  exp_a=np.exp(a-c)
  sum_exp_a=np.sum(exp_a)
  y=exp_a/sum_exp_a
  return y

In [12]:
a=np.array([0.3,2.9,4.0])
y=softmax(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0
