In [ ]:
import numpy as np
X=np.random.rand(2)
W=np.random.rand(2,3)
B=np.random.rand(3)

print(X.shape)
print(W.shape)
print(B.shape)

Y=np.dot(X,W)+B

(2,)
(2, 3)
(3,)


In [ ]:
X_dot_W = np.array([[0,0,0,],[10,10,10]])
B = np.array([1,2,3])

print(X_dot_W)
print(X_dot_W+B)

[[ 0  0  0]
 [10 10 10]]
[[ 1  2  3]
 [11 12 13]]


In [ ]:
dY = np.array([[1,2,3],[4,5,6]])
print(dY)
dB = np.sum(dY,axis=0)
print(dB)

[[1 2 3]
 [4 5 6]]
[5 7 9]


In [ ]:
class Affine:
  def __init__(self,W,b):
    self.W=W
    self.b=b
    self.x=None
    self.dW=None
    self.db=None

  def forward(self,x):
    self.x=x
    out=np.dot(x,self.W)
    return out

  def backward(self,dout):
    dx=np.dot(dout,self.W.T)
    self.dW=np.dot(self.x.T,dout)
    self.db=np.sum(dout,axis=0)
    return dx

In [ ]:
class SoftmaxWithLoss:
  def __init__(self,x,t):
    self.loss=None
    self.y=None
    self.x=None

    def forward(self,x,t):
      self.t=t
      self.y=softmax(x)
      self.loss=cross_entropy_error(self.y,self.t)
      return self.loss

    def backward(self,dout=1):
      batch_size=self.t.shape[0]
      dx=(self.y-self.t)/batch_size
      return dx